from django.contrib.gis.db import models

class SeptaStops(models.Model):
    gid = models.IntegerField(primary_key=True)

    route = models.IntegerField()
    direction = models.CharField(max_length=254)
    seq = models.IntegerField()
    stopabbr = models.CharField(max_length=254)
    stopid = models.IntegerField()
    stopname = models.CharField(max_length=254)
    routes = models.CharField(max_length=254)
    latitude = models.DecimalField(max_digits=65535, decimal_places=65534)
    longitude = models.DecimalField(max_digits=65535, decimal_places=65534)
    the_geom_2272 = models.PointField(srid=2272) # Degrees
    the_geom_4326 = models.PointField(srid=4326) # Local, feet
    the_geom_900913 = models.PointField(srid=900913) # Google, meters

    objects = models.GeoManager()

    class Meta:
        db_table = u'septa_stops'

class SeptaRoutes(models.Model):
    gid = models.IntegerField(primary_key=True)

    route = models.CharField(max_length=10)
    length = models.DecimalField(max_digits=65535, decimal_places=65534)
    label = models.CharField(max_length=5)
    snow = models.CharField(max_length=5)
    core = models.CharField(max_length=5)
    description = models.CharField(max_length=100)
    shape_len = models.DecimalField(max_digits=65535, decimal_places=65534)
    the_geom_2272 = models.MultiLineStringField(srid=2272) # Degrees
    the_geom_4326 = models.MultiLineStringField(srid=4326) # Local, feet
    the_geom_900913 = models.MultiLineStringField(srid=900913) # Google, meters

    objects = models.GeoManager()

    class Meta:
        db_table = u'septa_routes'


########################################
# The following classes were also generated by the manage.py inspectdb command,
# but I assume I don't need them.
#

#class GeographyColumns(models.Model):
#    f_table_catalog = models.TextField() # This field type is a guess.
#    f_table_schema = models.TextField() # This field type is a guess.
#    f_table_name = models.TextField() # This field type is a guess.
#    f_geography_column = models.TextField() # This field type is a guess.
#    coord_dimension = models.IntegerField()
#    srid = models.IntegerField()
#    type = models.TextField()
#    class Meta:
#        db_table = u'geography_columns'

#class GeometryColumns(models.Model):
#    f_table_catalog = models.CharField(max_length=256)
#    f_table_schema = models.CharField(max_length=256)
#    f_table_name = models.CharField(max_length=256)
#    f_geometry_column = models.CharField(max_length=256)
#    coord_dimension = models.IntegerField()
#    srid = models.IntegerField()
#    type = models.CharField(max_length=30)
#    class Meta:
#        db_table = u'geometry_columns'

#class SpatialRefSys(models.Model):
#    srid = models.IntegerField(primary_key=True)
#    auth_name = models.CharField(max_length=256)
#    auth_srid = models.IntegerField()
#    srtext = models.CharField(max_length=2048)
#    proj4text = models.CharField(max_length=2048)
#    class Meta:
#        db_table = u'spatial_ref_sys'
